#!/usr/bin/env sh
# Write office-addin/env-config.js. The add-in is served FROM the OWUI/guardproxy origin
# (/officeaddin/), so the OWUI base is SAME-ORIGIN (empty) — /api calls carry the session
# cookie automatically, no host to bake, nothing to type. Only the locked model id comes
# from .env (same one the browser side panel uses).
#   usage: sh gen-env-config.sh [path/to/.env]
set -e
here="$(cd "$(dirname "$0")" && pwd)"
env_file="${1:-$here/../.env}"
filter="gp-browser"
if [ -f "$env_file" ]; then
  v="$(grep -E '^GP_BROWSER_MODEL_ID=' "$env_file" | head -1 | cut -d= -f2- | tr -d '"'\'' \r\t')"
  [ -n "$v" ] && filter="$v"
fi
{
  printf '// generated by gen-env-config.sh — do not edit\n'
  printf 'window.GP_OWUI_BASE = "";            // same-origin (served under the OWUI host)\n'
  printf 'window.GP_MODEL_FILTER = "%s";\n' "$filter"
} > "$here/env-config.js"
echo "office-addin/env-config.js -> same-origin, model=$filter"
